### ISSUE TITLE
Getting TypeError

### ISSUE THREAD

**Issue by mady143** [adityasarvaiya/Automatic_Question_Generation#13]
Hi @adityasarvaiya @vishalbidawatka @Vrutti26 ,
I had successfully run the code without any dependency issues and but while selecting the file and click on the button Generate Questions getting an error like 
**TypeError: float() argument must be a string or a number**
in the line 
**num_sentences_selected = math.ceil(float(self.ratio) * sentence_length)** from Automatic_Question_Generation/aqg/utils/sentence_selection.py", line 126
could anyone help me please...

Thanks and Regards,
Manikantha Sekhar..

**Comment by adityasarvaiya** [comment]
Please check if you have created .env file correctly. Also check if this happens only with files or with any mode of input.
Also try to change __init__ function in sentence_selection.py to print if you are getting self.ratio correctly.
`def __init__(self):
        self.fr = File_Reader()
        self.ratio = os.environ.get("SENTENCE_RATIO")
        print ("ratio : " , self.ratio) 
        # self.ratio = 0.05
`
If you can't see self.ratio properly then remove above comment and set self.ratio manually. See it works then.

**Comment by mady143** [comment]
Hi @adityasarvaiya 
I had resolved the issue thank you @adityasarvaiya
